name: ci

on: [push, workflow_dispatch]

env:
  NODE_OPTIONS: --max-old-space-size=5000

jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , 'skip ci')"
    steps:
      - { uses: actions/checkout@v4, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v4, with: { node-version: 'lts/*', cache: 'yarn' } }
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test

  release-job:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    permissions:
      contents: write
      id-token: write
    steps:
      - { uses: actions/checkout@v4, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v4, with: { node-version: 'lts/*', cache: 'yarn' } }

      # Cache for npm/npx in ~/.npm
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-v1-${{ runner.os }}

      - run: yarn --frozen-lockfile
      - run: yarn build-prod

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx @naturalcycles/semantic-release
